theme: ''
title: iDEA.org.uk
description: iDEA is an international award winning project that helps you badge your brilliance. Through our series of online challenges and events, you can win career-enhancing badges, unlock new opportunities and, ultimately, gain internationally recognised awards that help you stand out from the crowd.